[tool.poetry]
name = "dynamic-cf-dns-resolve"
version = "0.1.0"
description = "Automaticlly update dns resolve of cloudflare by server's current ip."
authors = ["Xyz9Selu <xyz.9selu@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
click = "^8.1.8"
requests = "^2.32.3"
python-dotenv = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "tuna"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
priority = "primary"
